Added logic to support the possibility that the real mvn script cannot be found, closing #77.

diff --git a/bin/mvn b/bin/mvn
--- a/bin/mvn
+++ b/bin/mvn
@@ -195,6 +195,13 @@ done
 # Find the original mvn script
 MVN="`which -a mvn | sed -n '2p'`"
 
+[ -z "$MVN" ] && [ -n "$M2_HOME" ] && MVN="$M2_HOME/bin/mvn"
+
+if [ -z "$MVN" ]; then
+	echo "Cannot find real mvn script. Either add it to the \$PATH, or define a \$M2_HOME."
+	exit 1
+fi
+
 # Get help from the original mvn and then print our additional options
 if [ $HELP ]; then
 	$MVN $ARGS
