Added comments and debug statements, which closes #36.

diff --git a/bin/mvn b/bin/mvn
--- a/bin/mvn
+++ b/bin/mvn
@@ -7,26 +7,33 @@ DEFAULT_POM_TEMPLATE_PROPERTIES="pom-template.properties"
 
 #DEBUG="true"
 FP_POM_TEMPLATE_PROPERTIES=""
-FP_CACHE=""
 findProperties() {
 	[ "$DEBUG" ] && echo "\t1\tfindProperties()"
 	FP_POM_TEMPLATE_PROPERTIES_NAME="pom-template.properties"
 	DOT_DOT="../"
-	if [ ! "$FP_CACHE" ]; then
-		[ "$DEBUG" ] && echo "\t2\tfindProperties()"
-		FP_POM_TEMPLATE_PROPERTIES="$FP_POM_TEMPLATE_PROPERTIES_NAME"
-		FP_CWD=$DOT_DOT
-		FP_LAST_CWD=""
-		FP_IS_NOT_ROOT="false"
-		while [ ! -f "$FP_POM_TEMPLATE_PROPERTIES" ] && [ "$FP_IS_NOT_ROOT" != "" ]; do
-			[ "$DEBUG" ] && echo "\t3\tfindProperties()"
-			FP_POM_TEMPLATE_PROPERTIES="${DOT_DOT}${FP_POM_TEMPLATE_PROPERTIES}"
-			FP_LAST_CWD=$FP_CWD
-			FP_CWD="${DOT_DOT}${FP_CWD}"
-			# FIXME: This is not the best way to determine if we are at the root.
-			FP_IS_NOT_ROOT="`diff $FP_LAST_CWD $FP_CWD`"
-		done
-		FP_CACHE=true
+
+	# Return if we have already done the work to find pom-template.properties
+	[ "$FP_POM_TEMPLATE_PROPERTIES" ] && return;
+	FP_POM_TEMPLATE_PROPERTIES="$FP_POM_TEMPLATE_PROPERTIES_NAME"
+	FP_CWD=$DOT_DOT
+	FP_LAST_CWD=""
+	FP_IS_NOT_ROOT="false"
+
+	# While we have not found pom-template.properties, and we haven't hit the root
+	while [ ! -f "$FP_POM_TEMPLATE_PROPERTIES" ] && [ "$FP_IS_NOT_ROOT" != "" ]; do
+		[ "$DEBUG" ] && echo "\t2\tfindProperties::while(! -f $FP_POM_TEMPLATE_PROPERTIES && \$FP_IS_NOT_ROOT)"
+		FP_POM_TEMPLATE_PROPERTIES="${DOT_DOT}${FP_POM_TEMPLATE_PROPERTIES}"
+		FP_LAST_CWD=$FP_CWD
+		FP_CWD="${DOT_DOT}${FP_CWD}"
+		# FIXME: This is not the best way to determine if we are at the root.
+		FP_IS_NOT_ROOT="`diff $FP_LAST_CWD $FP_CWD`"
+	done
+
+	# If we have still not found pom-template.properties, exit with an error
+	if [ ! -f "$FP_POM_TEMPLATE_PROPERTIES" ]; then
+		[ "$DEBUG" ] && echo "\t3\tfindProperties::while::if(! -f $FP_POM_TEMPLATE_PROPERTIES)"
+		echo "ERROR: Unable to find pom-template.properties"
+		exit 1
 	fi
 }
 
@@ -36,6 +43,8 @@ newer_than() {
 	FILE_1=$1
 	FILE_2=$2
 	FILE_1_NAME="`basename $FILE_1`"
+
+	# Use ls to list and sort the 2 files by their update time
 	NEWER_THAN="`ls -xt $FILE_1 $FILE_2 | awk '{print $1}' | xargs basename`"
 #	[ "$DEBUG" ] && echo "newer_than($1, $2): $NEWER_THAN"
 	[ "$NEWER_THAN" = "$FILE_1_NAME" ] && return 1 || return 0;
@@ -50,9 +59,20 @@ updatePOM() {
 	UP_POM="`echo $UP_POM_TEMPLATE | sed 's/-template//'`"
 
 	findProperties;
+
+	# Determine if the pom.xml file needs to be created by checking if:
+	# 1) POM-TEMPLATE_PROPERTIES is newer than POM
+	# 2) POM-TEMPLATE is newer than POM
 	if [ ! -f "$UP_POM" ] || [ "`newer_than $UP_POM_TEMPLATE $UP_POM; echo $?`" = "1" ] || [ "`newer_than $FP_POM_TEMPLATE_PROPERTIES $UP_POM; echo $?`" = "1" ]; then
-		[ "$DEBUG" ] && echo "\t2\tupdatePOM($UP_POM_TEMPLATE, $UP_PARENT_POM_TEMPLATE)"
+		[ "$DEBUG" ] && echo "\t2\tupdatePOM::if(newer_than(...))"
+
+		# Read pom-template.properties and sort the contents by the number of "."
+		# characters in the name of each name=value pair (in descending order).
 		PROPERTIES=`awk -F\. '{print NF " " $0} ' $FP_POM_TEMPLATE_PROPERTIES | sort -r | awk '{print $2}' | grep -v '^$'`
+
+		# Generate a script to replace all occurances of each property with its value
+		# such that ${name} gets replaced with value. Also replace all references to
+		# POM-TEMPLATE with POM
 		UPDATE_CMD="`echo \"$PROPERTIES\" | sed 's/$/ DELIMITER_STRING/' | xargs echo | sed 's/\(\s*=\s*\)\([^ ]*\)\( DELIMITER_STRING\)/\\\\\\\\\\\\\\\\\\\\(\\\\\\\\\\\\\\\\\\\\(\\\\\\\\\\\\\\\\\\\\)\\\\\\\\\\\\\\\\\\\\|\\\\\\\\\\\\\\\\\\\\([-\.a-zA-Z]*\\\\\\\\\\\\\\\\\\\\)\\\\\\\\\\\\\\\\\\\\)\\\\\\\\\\\\\\\\\\\\}\/\2\/g/g' | sed 's/\(\( \)\|\(^\)\)\([a-zA-Z0-9]*\)/\1\-e \\\\s\/\\\\\\$\\\\{\4/g' | sed \s/\^/\-e\ \'s\\\/$UP_PARENT_POM_TEMPLATE\\\/$UP_PARENT_POM\\\/g\'\ /` $UP_POM_TEMPLATE"
 		echo $UPDATE_CMD | xargs sed > $UP_POM
 		echo "Updated: $UP_POM"
@@ -61,9 +81,17 @@ updatePOM() {
 
 updateParentPOMs() {
 	UPP_POM_TEMPLATE="$1"
+	[ "$DEBUG" ] && echo "\t1\tupdateParentPOMs($UPP_POM_TEMPLATE)"
 	UPP_PARENT_POM_TEMPLATE=$DEFAULT_POM_TEMPLATE
+
+	# While there exists a parent POM-TEMPLATE
 	while [ -f $UPP_POM_TEMPLATE ]; do
+		[ "$DEBUG" ] && echo "\t2\tupdateParentPOMs::while(-f $UPP_POM_TEMPLATE)"
 		UPP_PARENT_POM_TEMPLATE="../$UPP_PARENT_POM_TEMPLATE"
+
+		# If a <relativePath/> tag exists, set the next parent using the relative path
+		# FIXME: The relativePath string can occur anywhere in the document, so
+		# this may lead to a false positive
 		if [ "`cat $UPP_POM_TEMPLATE | grep relativePath`" ]; then
 			UPP_PARENT_POM_TEMPLATE="`cat $UPP_POM_TEMPLATE | sed 's/<relativePath>//' | sed 's/<\/relativePath>//'`"
 		fi
@@ -78,14 +106,24 @@ UCP_OUTER_MODULES=""
 updateChildPOMs() {
 	UCP_FILE_NAME="$1"
 	UCP_OUTER_MODULES="./"
+	[ "$DEBUG" ] && echo "\t1\tupdateChildPOMs($UCP_FILE_NAME)"
+
+	# While there are modules to process
 	while [ "$UCP_OUTER_MODULES" != "" ]; do
+		[ "$DEBUG" ] && echo "\t2\tupdateChildPOMs::while($UCP_OUTER_MODULES)"
+
+		# For each module in the OUTER modules list
 		for UCP_CHILD_MODULE in $UCP_OUTER_MODULES; do
-			# Make sure that the POM-TEMPLATE file exists
+			[ "$DEBUG" ] && echo "\t3\tupdateChildPOMs::while::for($UCP_CHILD_MODULE)"
+			# Make sure that the POM-TEMPLATE file exists in the module
 			if [ -f ${UCP_CHILD_MODULE}${UCP_FILE_NAME} ]; then
+				[ "$DEBUG" ] && echo "\t4\tupdateChildPOMs::while::for::if(-f ${UCP_CHILD_MODULE}${UCP_FILE_NAME})"
 				# Get all module entries and remove <module>, </module> and <!--.*-->
 				UCP_UCP_CHILD_MODULE_MODULES="`grep '<module>' ${UCP_CHILD_MODULE}${UCP_FILE_NAME} | sed 's/\(\(\(<\)\|\(<\/\)\)module>\)\|\(<!--.*-->\)//g' | xargs echo`"
-				# If we have modules
+
+				# If the module has modules of its own
 				if [ "$UCP_UCP_CHILD_MODULE_MODULES" != "" ]; then
+					[ "$DEBUG" ] && echo "\t5\tupdateChildPOMs::while::for::if::if($UCP_UCP_CHILD_MODULE_MODULES)"
 					# Define the dir that the module is in, and escape the "/"
 					ESCAPED_DIR="`echo "$UCP_CHILD_MODULE/" | sed 's/\//\\\\\//g'`"
 					# Prepend all module names with the appropriate parent module dir
@@ -98,7 +136,7 @@ updateChildPOMs() {
 			fi
 		done
 
-		# Overwrite the UCP_FILE_NAME to the default pom-template.xml
+		# Overwrite the UCP_FILE_NAME to the default POM-TEMPLATE
 		UCP_FILE_NAME="/$DEFAULT_POM_TEMPLATE"
 
 		# Append the UCP_INNER_MODULES list to UCP_ALL_MODULES
@@ -117,7 +155,9 @@ updateChildPOMs() {
 
 	# Iterate through the UCP_ALL_MODULES list
 	for UCP_POM_TEMPLATE in $UCP_ALL_MODULES; do
-		# Call updatePOM with the default pom-template.xml as the parent pom
+		[ "$DEBUG" ] && echo "\t5\tupdateChildPOMs::for($UCP_POM_TEMPLATE)"
+
+		# Call updatePOM with the default POM-TEMPLATE as the parent pom
 		updatePOM $UCP_POM_TEMPLATE/$DEFAULT_POM_TEMPLATE $DEFAULT_POM_TEMPLATE
 	done
 }
@@ -152,25 +192,8 @@ while [ $# != 0 ]; do
 	shift
 done
 
-# Update all parent POMs
-updateParentPOMs $POM_TEMPLATE;
-
-# Update all child POMs
-updateChildPOMs $POM_TEMPLATE;
-
-# If we only want to update from the template poms, then exit now
-if [ $UPDATE_TEMPLATES ]; then
-	exit 0;
-fi
-
 # Find the original mvn script
 MVN="`which -a mvn | sed -n '2p'`"
-
-# If goal=clean, then set maven.test.skip=true (this should already be the
-# default in maven.
-if [ $CLEAN ]; then
-	ARGS="-Dmaven.test.skip $ARGS"
-fi
 
 # Get help from the original mvn and then print our additional options
 if [ $HELP ]; then
@@ -182,6 +205,23 @@ if [ $HELP ]; then
 	echo " -ft                           Force the use of an alternate POM-TEMPLATE"
 	echo "                               file."
 	exit
+fi
+
+# Update all parent POMs
+updateParentPOMs $POM_TEMPLATE;
+
+# Update all child POMs
+updateChildPOMs $POM_TEMPLATE;
+
+# If we only want to update from the template poms, then exit now
+if [ $UPDATE_TEMPLATES ]; then
+	exit 0;
+fi
+
+# If goal=clean, then set maven.test.skip=true (this should already be the
+# default in maven.
+if [ $CLEAN ]; then
+	ARGS="-Dmaven.test.skip $ARGS"
 fi
 
 $MVN $ARGS
