Added logic to check whether the original mvn script can be located, and throws an error if it can not be, closing #122.

diff --git a/maven/core/src/bin/mvn b/maven/core/src/bin/mvn
--- a/maven/core/src/bin/mvn
+++ b/maven/core/src/bin/mvn
@@ -260,13 +260,19 @@ while [ -n "$1" ]; do
 done
 
 # Find the original mvn script
+THIS_MVN="`which mvn`"
 MVN="`which -a mvn | sed -n '2p'`"
+if [ ! -f "$MVN" ] || [ "$MVN" = "$THIS_MVN" ]; then
+	if [ -z "$M2_HOME" ]; then
+		echo "Error: M2_HOME is not defined correctly."
+		exit 1
+	fi
 
-[ -z "$MVN" ] && [ -n "$M2_HOME" ] && MVN="$M2_HOME/bin/mvn"
-
-if [ -z "$MVN" ]; then
-	echo "Cannot find real mvn script. Either add it to the \$PATH, or define a \$M2_HOME."
-	exit 1
+	MVN="$M2_HOME/bin/mvn"
+	if [ ! -f "$MVN" ] || [ "$MVN" = "$THIS_MVN" ]; then
+		echo "Error: Unable to find install of m2. The mvn script is neither in the PATH nor at \$M2_HOME/bin/mvn"
+		exit 1
+	fi
 fi
 
 # Get help from the original mvn and then print our additional options
